# NumPy란?
- NumPy(Numerical Python)는 다차원 배열의 연산 기능을 모아 놓은 꾸러미이며, 수치 연산을 위한 다양한 기능을 제공하는 파이썬 라이브러리
- 다차원 배열의 연산 기능과 함께 데이터를 효율적으로 저장하고 빠르게 연산할 수 있도록 설계되어 있음
- 대규모 데이터를 효율적으로 저장하고 빠르게 계산할 수 있으며, 반복 연산이나 행렬 연산이 많은 데이터 분석, 과학적 계산, 등에서 성능을 크게 향상시킬 수 있음

In [2]:
# NumPy 패키지 설치
! pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ------- -------------------------------- 2.4/12.6 MB 13.5 MB/s eta 0:00:01
   ------------------ --------------------- 5.8/12.6 MB 13.1 MB/s eta 0:00:01
   ---------------------------------------  12.6/12.6 MB 20.5 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 18.5 MB/s eta 0:00:00



[notice] A new release of pip is available: 24.2 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
# 설치된 NumPy 버전을 출력
import numpy
print(numpy.__version__)

2.2.1


# 배열이란?
- NumPy는 기본적인 자료구조로 배열(array)을 사용
- 배열은 데이터를 효율적으로 처리하기 위한 자료구조
- 연속적으로 데이터를 담을 수 있는 객체이며, array라고 씀
- 파이썬에서는 고성능 배열 작업을 위해 NumPy 라이브러리를 사용하는 것이 일반적

# 배열의 주요 특징
- 같은 종류의 데이터만 담을 수 있다.
- 차원을 갖는다.(1차원, 2차원, 3차원 등)
- 빠르고 간단하게 연산을 처리할 수 있다.(모든 요소에 한번에 연산을 적용 가능)

In [7]:
# np.array(요소가 나열된 형태의 객체) -> 리스트, 튜플 range 등의 형태의 객체를 사용해서 배열을 만들 수 있음
# 리스트로 배열 만들기
import numpy as np

list1 = [1, 2, 3]

arr1 = np.array(list1)

arr1

array([1, 2, 3])

In [8]:
# np.zeros(배열의 모양) -> np.zeros()를 사용하여 0으로 초기화된 배열을 만들 수 있음
# 배열의 차원을 나타내기 위한 정수나 튜플형을 인자로 사용
# 5개의 0으로 채워진 배열 만들기
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
# (2, 4) 튜플을 사용해 0으로 초기화된 2차원 배열 만들기
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
# np.ones(배열의 모양) -> 1로 초기화된 배열 생성하기
# 7개의 1로 채워진 배열 만들기
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [11]:
# np.arange([시작 번호], 끝 번호, [건너 뛰는 수]) -> 연속된 숫자를 채워서 배열 만들기
# range()와 마찬가지로 끝 번호 미만의 숫자까지 생성
# np.arange 사용하기
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(20, 30, 2)

array([20, 22, 24, 26, 28])

In [14]:
# np.random.rand(배열의 모양) -> 정해진 숫자가 아닌 랜덤값으로 배열 만들기
# 랜덤값 배열 만들기
np.random.rand(2, 3)

array([[0.62006808, 0.50580302, 0.62413664],
       [0.95419989, 0.07433548, 0.86890375]])

# 배열의 차원 변경하기
- 1차원 배열을 만들고, 차원을 변형할 수 있음
- reshape()을 사용하여 차원 변형이 가능
- array.reshape(변형할 모양)

In [16]:
# 16개의 값이 들어 있는 배열을 (4,4) 형태의 2차원 배열로 변형하기
arr2 = np.arange(16)
arr2.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
# 16개의 값이 들어 있는 배열을 (2, 2, 4) 형태의 배열로 변형하기
arr2 = np.arange(16)
arr2.reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

# 배열의 형태 및 데이터 타입 확인하기
- 배열은 같은 종류의 데이터만 담을 수 있으며 차원을 가지는 특징이 있음
- 배열 안에 담긴 데이터 타입이 무엇인지, 그리고 어떤 차원과 형태를 가지는지 살펴보는 방법도 존재
- 또한, 배열 안에 담긴 데이터 타입을 다른 타입으로 변환도 가능
- shape -> 배열의 형태 확인
- dtype() -> 배열의 데이터 타입 확인
- astype() -> 배열의 데이터 타입 변경

In [29]:
# 0부터 9까지 숫자가 담긴 배열 생성
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# 배열의 형태 알아보기
arr.shape

# 10개의 값을 가지는 1차원 배열의 형태임을 확인 가능

(10,)

In [31]:
# 배열에 포함된 데이터의 자료형 알아보기
arr.dtype

# 모든 데이터 타입이 int64로 정수형의 데이터가 들어있음

dtype('int64')

In [34]:
# 배열에 들어 있는 데이터를 실수로 변환하기
arr.astype(float)

# 각각의 데이터가 소수점이 붙어 있는 실수형으로 변환되어 출력

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])