# 배열의 값 선택하기
- 배열도 리스트와 마찬가지로 인덱스를 사용하여 원하는 값을 선택할 수 있음
- 마이너스 인덱스와 슬라이싱을 사용한 범위 지정 역시 가능
- 배열의 인덱스를 활용하여 새로운 값을 할당할 수도 있음

In [19]:
# 배열 인덱스 사용하여 원하는 값 선택하기
# 0부터 15까지의 숫자가 담긴 arr라는 배열을 생성
import numpy as np
arr = np.arange(16)

# 5번 인덱스에 저장된 값을 출력
print(arr[5])

# 마이너스 인덱스를 사용하여 가장 마지막에 위치한 인덱스 값을 출력
print(arr[-1])

# 슬라이싱을 활용하여 5번 인덱스부터 7번 인덱스에 저장된 값을 추출
print(arr[5:8])

5
15
[5 6 7]


In [10]:
# 1차원 배열의 인덱스를 활용해 새로운 값 할당하기
arr[5] = 100
arr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [11]:
# 슬라이싱을 활용해 여러 값 할당하기
arr[6:8] = [200, 201]
arr

array([  0,   1,   2,   3,   4, 100, 200, 201,   8,   9,  10,  11,  12,
        13,  14,  15])

In [12]:
# 다차원 배열의 인덱스를 활용해 새로운 값 할당하기
# 다차원 배열 생성
arr2 = np.arange(16).reshape(4, 4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
print(arr2[1])
print(arr2[1][1])
print(arr2[1, 2]) # arr2[1][2]와 동일

[4 5 6 7]
5
6


In [23]:
arr2[1, 2] = 100 # 새로운 값 할당
arr2

array([[  0,   1,   2,   3],
       [  4,   5, 100,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15]])

In [25]:
# 다차원 배열에서 슬라이싱 활용하기
arr2[0:2]

array([[  0,   1,   2,   3],
       [  4,   5, 100,   7]])

In [26]:
arr2[0:2, 2:4]

array([[  2,   3],
       [100,   7]])

# 불리언 인덱스
- 배열에서 읽어오고 싶은 값이 위치한 곳에는 True를, 그렇지 않은 위치에는 False를 넣은 불리언 배열을 만들어서 값을 선택하는 방법을 불리언 인덱스라고 함
- 조건에 만족하는 인덱스에만 True 값을 담고, 그렇지 않은 곳에는 False를 담은 배열을 만들어 활용할 수 있음
- 불리언 배열을 인덱스로 사용하면 True에 위치한 값만 반환하게 됨
- 불리언 인덱스는 특정 조건을 만족하는 값을 선택(필터링) 할 때 많이 사용됨

In [33]:
# 점수를 담은 배열 생성하기
scores = [80, 90, 70, 65, 85, 95, 90, 80, 75, 80]
score_arr = np.array(scores)
score_arr

array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])

In [34]:
# 불리언 배열 만들기
score_arr >= 90

array([False,  True, False, False, False,  True,  True, False, False,
       False])

In [35]:
# 불리언 인덱스 활용하기 -> True에 위치한 값만 반환
score_arr[score_arr >= 90]

array([90, 95, 90])

In [36]:
# 불리언 인덱스 활용해 값 선택하고 변경하기 -> True에 위치한 값만 변경됨
score_arr[score_arr >= 90] = 999
score_arr

array([ 80, 999,  70,  65,  85, 999, 999,  80,  75,  80])