In [ ]:
# NumPy로 연산하기
# 반복문을 사용하지 않고 배열 전체를 하나의 숫자처럼 연산식을 작성해도 각각의 원소에 연산 결과가 적용됨

import numpy as np
arr = np.arange(1, 5)
arr

array([1, 2, 3, 4])

In [3]:
# 더하기 연산
arr + 2

array([3, 4, 5, 6])

In [4]:
# 곱하기 연산
arr * 2

array([2, 4, 6, 8])

In [10]:
# (참고)리스트는 정수형 데이터와 더하기 연산은 불가능하며, 곱하기 연산의 경우 리스트 전체가 복사되는 형태로 처리
list = [1, 2, 3, 4]
print(list)

list2 = list * 2
print(list2)

[1, 2, 3, 4]
[1, 2, 3, 4, 1, 2, 3, 4]


In [13]:
# 배열과 배열의 덧셈 연산 수행하기
# 새로운 배열 생성
arr1 = np.arange(5, 9)
arr1

array([5, 6, 7, 8])

In [14]:
# 배열과 배열의 덧셈은 같은 인덱스에 위치한 값의 덧셈 연산으로 처리
arr1 + arr

array([ 6,  8, 10, 12])

In [15]:
# 제곱
np.square(arr)

array([ 1,  4,  9, 16])

In [16]:
# 제곱근(루트)
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [18]:
# 더하기
np.add(arr, arr1) # arr + arr1과 동일

array([ 6,  8, 10, 12])

In [19]:
# 합계
np.sum(arr)

np.int64(10)

In [20]:
# 평균
np.mean(arr)

np.float64(2.5)

In [21]:
# 표준편차
np.std(arr)

np.float64(1.118033988749895)

In [22]:
# 최소값
np.min(arr)

np.int64(1)

In [23]:
# 최대값
np.max(arr)

np.int64(4)

# 배열의 차원과 모양 변형하기
- reshape()를 호출하여 생성한 배열의 차원과 모양을 바꿀 수 있음
- 기존에 있는 배열의 축을 바꾸기 위해서는 transpose()를 사용

# transpose(축)
- 1차원 배열의 경우 배열의 축을 전환하더라도 동일한 배열을 반환
- 2차원 이상의 배열의 경우 축을 전환한 배열을 반환

In [24]:
# 배열의 축 변형하기
# 2차원 배열 생성
import numpy as np
arr = np.arange(10).reshape(2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
# 2차원 배열의 축 변형
# 첫번째 행에 있는 값들이 첫번째 열에 위치, 두번째 행에 있는 값들이 두번째 열에 위치하도록 변환됨
arr.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [26]:
# 3차원 배열 생성
arr3d = np.arange(27).reshape(3, 3, 3)
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [27]:
# 3차원 배열 변형하기
# 기본 x, y, z 축의 순서대로 0, 1, 2의 숫자로 표현
# transpose()를 호출할 때 각 축의 위치를 인자로 설정하여 넘겨줌
# 아무 값도 넘겨주지 않을 경우, 기본 순서(0, 1, 2)의 역순(2, 1, 0)에 해당하는 값으로 축이 설정되어 변환됨

arr3d.transpose() # transpose(2, 1, 0)과 동일


array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [28]:
arr3d.transpose(1, 0, 2)

array([[[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20]],

       [[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23]],

       [[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26]]])